### PR TITLE
Add feature to plot from polars dataframes

### PR DESCRIPTION
**Pull request by ptiza**
Implements #24 

This needs serialization into JSON  rows from column based polars format.

### CODE REVIEW

**Comment by ThomAub** [comment]
Thanks for having a look at this issue ! I will try this shortly

**Review by davidB — APPROVED** [review]
Thanks for the contribution with  example & feature

**Comment by davidB** [comment]
I don't know why the CI was stopped (maybe a timeout, as ci was long before and polars could also take time).
I'll take a look to the workflow later, feel free to include update of the workflow into you PR ;-)

**Comment by ptiza** [comment]
I updated the CI workflow, for me it ran fine on my test branch...

**Comment by ptiza** [comment]
Hmm seems like code coverage lets Ubuntu run out of space.. maybe we need to free up space on the runner e.g. with https://github.com/jlumbroso/free-disk-space

**Comment by ptiza** [comment]
Please approve CI workflow again, it should be green now.

**Review by davidB — APPROVED** [review]

**Comment by ptiza** [comment]
Wow... now the azure apt mirror timed out during disk space clean, please retry...

**Comment by ptiza** [comment]
Please approve CI workflow again, thanks

**Comment by ptiza** [comment]
Thank you! Finally, all green... Can be merged, I guess..

**Comment by davidB** [comment]
Thank you, we'll do a release next week-end (you can ping me, next week if I forgot ;-) )

**Pull request merged**
